### ISSUE TITLE
Unable to install in windows

### ISSUE THREAD

**Issue by AlexJangam** [alanclarke/int-encoder#1]
Its using bignum which internally uses expresso, which when installed is causing errors and uninstalling  to previous state.

Please share some alternate solution for the functionality.

Error Log:
module.js:355
  Module._extensions[extension](this, filename)
Error: %1 is not a valid Win32 application.
- Occured at bignum.node when i installed individually.

**Comment by alanclarke** [comment]
Hi @AlexJangam, thanks for reporting this. It looks like the issue lies with bignum. I guess we could shop around for an alternative to bignum. Happy to accept a pr for one if it looks decent and passes the test suite

**Comment by alanclarke** [comment]
https://github.com/alanclarke/int-encoder/pull/2
